# Generated by Django 3.2.8 on 2021-10-16 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, choices=[('ปริญญาตรี', 'ปริญญาตรี'), ('ปริญญาโท', 'ปริญญาโท'), ('ปริญญาเอก', 'ปริญญาเอก')], max_length=50, null=True)),
                ('faculty', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('study_date', models.DateField(blank=True, default=None)),
                ('graduate', models.DateField(blank=True, default=None)),
                ('gpa', models.FloatField()),
                ('honors', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('completed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Degee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.degree')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('id_Position', models.CharField(max_length=20)),
                ('title_name', models.CharField(blank=True, choices=[('นาย', 'นาย'), ('นาง', 'นาง'), ('นางสาว', 'นางสาว')], max_length=10, null=True)),
                ('name_th', models.CharField(max_length=100)),
                ('name_eng', models.CharField(max_length=100)),
                ('personal_type', models.CharField(blank=True, choices=[('พนักงานมหาวิทยาลัย', 'พนักงานมหาวิทยาลัย'), ('ลูกจ้างชั่วคราว', 'ลูกจ้างชั่วคราว')], max_length=255, null=True)),
                ('line_of_work', models.CharField(blank=True, choices=[('วิชาการ', 'วิชาการ'), ('สนับสนุน', 'สนับสนุน')], max_length=100, null=True)),
                ('position', models.CharField(blank=True, choices=[('อาจารย์', 'อาจารย์'), ('เจ้าหน้าที่บริหารงานทั้วไป', 'เจ้าหน้าที่บริหารงานทั้วไป'), ('บุคลากร', 'บุคลากร'), ('นักวิชาการศึกษา', 'นักวิชาการศึกษา'), ('นักวิเคราะห์นโยบายและเเผน', 'นักวิเคราะห์นโยบายและเเผน'), ('นักประชาสัมพันธ์', 'นักประชาสัมพันธ์'), ('นักวิทยาศาสตร์', 'นักวิทยาศาสตร์'), ('นักวิชาการโสตทัศนศึกษา', 'นักวิชาการโสตทัศนศึกษา'), ('นักวิชาการคอมพิวเตอร์', 'นักวิชาการคอมพิวเตอร์'), ('ครู', 'ครู')], max_length=100, null=True)),
                ('academic_position', models.CharField(blank=True, choices=[('ศาสตราจารย์', 'ศาสตราจารย์'), ('รองศาสตราจารย์', 'รองศาสตราจารย์'), ('ผู้ช่วยศาสตราจารย์', 'ผู้ช่วยศาสตราจารย์'), ('เชี่ยวชาญ', 'เชี่ยวชาญ'), ('ชำนาญการพิเศษ', 'ชำนาญการพิเศษ'), ('ชำนาญการ', 'ชำนาญการ')], max_length=100, null=True)),
                ('director_position', models.CharField(blank=True, choices=[('คณบดี', 'คณบดี'), ('รองคณบดี', 'รองคณบดี'), ('ผู้ช่วยคณบดี', 'ผู้ช่วยคณบดี'), ('ประธานหลักสูตร', 'ประธานหลักสูตร'), ('หัวหน้างาน', 'หัวหน้างาน')], max_length=100, null=True)),
                ('start_work_date', models.DateField(blank=True, default=None)),
                ('placement_date', models.DateField(blank=True, default=None)),
                ('status_job', models.DateField(blank=True, default=None)),
                ('date_birth', models.DateField(blank=True, default=None)),
                ('nationality', models.CharField(max_length=100)),
                ('religion_con', models.CharField(blank=True, choices=[('พุทธ', 'พุทธ'), ('คริสต์', 'คริสต์'), ('อิสลาม', 'อิสลาม'), ('ยิว', 'ยิว'), ('ซิกข์', 'ซิกข์'), ('บาไฮ', 'บาไฮ'), ('โซโรอัสเตอร์', 'โซโรอัสเตอร์'), ('พราหมณ์-ฮินดู', 'พราหมณ์-ฮินดู'), ('เชน', 'เชน'), ('ไม่มีศาสนา', 'ไม่มีศาสนา')], max_length=100, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('email_UP', models.EmailField(max_length=255)),
                ('email_private', models.EmailField(max_length=255)),
                ('address', models.TextField()),
                ('faculty_id', models.ManyToManyField(to='account.Faculty')),
                ('id_degree', models.ManyToManyField(to='account.User_Degee')),
            ],
        ),
    ]
