# Generated by Django 3.2.8 on 2021-10-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_degee',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_degree',
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='degree',
            field=models.CharField(blank=True, choices=[('ปริญญาตรี', 'ปริญญาตรี'), ('ปริญญาโท', 'ปริญญาโท'), ('ปริญญาเอก', 'ปริญญาเอก')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='faculty',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gpa',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='graduate',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='honors',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='province',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='study_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.DeleteModel(
            name='User_Degee',
        ),
    ]
