# Generated by Django 3.2.8 on 2021-10-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211018_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
