# Generated by Django 3.2.8 on 2021-10-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_academic_manpower_academice_outstand_approval_budget_document_event_human_resource_leave_time_pendin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academice_outstand',
            name='year',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='user',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='document',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='event',
            name='year',
        ),
        migrations.RemoveField(
            model_name='human_resource',
            name='year',
        ),
        migrations.RemoveField(
            model_name='pending',
            name='user',
        ),
        migrations.RemoveField(
            model_name='report',
            name='year',
        ),
        migrations.RemoveField(
            model_name='service_manpower',
            name='year',
        ),
        migrations.RemoveField(
            model_name='service_outstand',
            name='year',
        ),
        migrations.RemoveField(
            model_name='study_leave',
            name='time',
        ),
        migrations.DeleteModel(
            name='Academic_Manpower',
        ),
        migrations.DeleteModel(
            name='Academice_Outstand',
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Human_resource',
        ),
        migrations.DeleteModel(
            name='leave_time',
        ),
        migrations.DeleteModel(
            name='Pending',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Service_Manpower',
        ),
        migrations.DeleteModel(
            name='Service_Outstand',
        ),
        migrations.DeleteModel(
            name='Study_leave',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
        migrations.DeleteModel(
            name='Year_plan',
        ),
    ]
