# Generated by Django 3.2.8 on 2021-10-20 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0011_auto_20211020_1525'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='leave_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('extend_time', models.IntegerField()),
                ('extend_begin', models.DateField()),
                ('extend_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Year_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Study_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('ปริญญาโท', 'ปริญญาโท'), ('ปริญญาเอก', 'ปริญญาเอก')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_time', models.CharField(max_length=255)),
                ('bursary', models.CharField(max_length=255)),
                ('work', models.DateField()),
                ('approval', models.DateField()),
                ('requesting', models.DateField()),
                ('time', models.ManyToManyField(null=True, to='data.leave_time')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Outstand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=1)),
                ('type_a', models.EmailField(default='-', max_length=255, null=True)),
                ('name', models.EmailField(default='-', max_length=255, null=True)),
                ('year', models.ManyToManyField(null=True, to='data.Year')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Manpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('bhd', models.IntegerField(blank=True, default='-', null=True)),
                ('master', models.IntegerField(blank=True, default='-', null=True)),
                ('sf', models.IntegerField(blank=True, default='-', null=True)),
                ('specific_sf', models.IntegerField(blank=True, default='-', null=True)),
                ('prof', models.IntegerField(blank=True, default='-', null=True)),
                ('specific_prof', models.IntegerField(blank=True, default='-', null=True)),
                ('work', models.IntegerField(blank=True, default='-', null=True)),
                ('leave', models.IntegerField(blank=True, default='-', null=True)),
                ('total', models.IntegerField()),
                ('year', models.ManyToManyField(null=True, to='data.Year')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='default.pdf', upload_to='uploads/%Y/%m/%d/')),
                ('year', models.ManyToManyField(null=True, to='data.Year')),
            ],
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_request', models.DateField()),
                ('date_request_evaluate', models.DateField()),
                ('date_evaluate', models.DateField()),
                ('date_begin', models.DateField()),
                ('date_full_term', models.DateField()),
                ('position_rc', models.CharField(max_length=255)),
                ('situation', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Human_resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='default.pdf', upload_to='uploads/%Y/%m/%d/')),
                ('year', models.ManyToManyField(null=True, to='data.Year_plan')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('train_people', models.IntegerField(blank=True, default='-', null=True)),
                ('train_time', models.IntegerField(blank=True, default='-', null=True)),
                ('seminar_people', models.IntegerField(blank=True, default='-', null=True)),
                ('seminar_time', models.IntegerField(blank=True, default='-', null=True)),
                ('observe_people', models.IntegerField(blank=True, default='-', null=True)),
                ('observe_time', models.IntegerField(blank=True, default='-', null=True)),
                ('faculty', models.ManyToManyField(null=True, to='account.Faculty')),
                ('year', models.ManyToManyField(null=True, to='data.Year')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=255)),
                ('date_request', models.DateField()),
                ('date_evaluate', models.DateField()),
                ('date_expire', models.DateField()),
                ('level_evaluate_tech', models.CharField(max_length=255)),
                ('level_evaluate_document', models.CharField(max_length=255)),
                ('no_evaluate', models.IntegerField()),
                ('faculty', models.ManyToManyField(null=True, to='account.Faculty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budgetyear', models.CharField(max_length=4)),
                ('initial_budget', models.IntegerField(blank=True, default='-', null=True)),
                ('total_budget', models.IntegerField(blank=True, default='-', null=True)),
                ('balance', models.IntegerField(blank=True, default='-', null=True)),
                ('faculty', models.ManyToManyField(null=True, to='account.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('อนุมัติ', 'อนุมัติ'), ('ไม่อนุมัติ', 'ไม่อนุมัติ')], max_length=10)),
                ('position', models.CharField(max_length=255)),
                ('faculty_academic', models.CharField(max_length=255)),
                ('date_request', models.DateField()),
                ('date_approval', models.DateField()),
                ('document', models.TextField()),
                ('publicity', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Academice_Outstand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=1)),
                ('type_a', models.EmailField(default='-', max_length=255, null=True)),
                ('name', models.EmailField(default='-', max_length=255, null=True)),
                ('year', models.ManyToManyField(null=True, to='data.Year')),
            ],
        ),
        migrations.CreateModel(
            name='Academic_Manpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.IntegerField(blank=True, default='-', null=True)),
                ('phd', models.IntegerField(blank=True, default='-', null=True)),
                ('exteach', models.IntegerField(blank=True, default='-', null=True)),
                ('teach', models.IntegerField(blank=True, default='-', null=True)),
                ('asst_prof', models.IntegerField(blank=True, default='-', null=True)),
                ('assoc_prof', models.IntegerField(blank=True, default='-', null=True)),
                ('work', models.IntegerField(blank=True, default='-', null=True)),
                ('leave', models.IntegerField(blank=True, default='-', null=True)),
                ('total', models.IntegerField()),
                ('faculty', models.ManyToManyField(null=True, to='account.Faculty')),
                ('year', models.ManyToManyField(null=True, to='data.Year')),
            ],
        ),
    ]
